name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: |
        npm install
        npm run build

    - name: FTP Deploy with retry
      uses: SamKirkland/FTP-Deploy-Action@v4.3.1
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftp
        port: 21
        local-dir: dist/
        server-dir: /public_html/
      continue-on-error: true

    - name: Retry FTP Deploy (if first failed)
      if: failure()
      uses: SamKirkland/FTP-Deploy-Action@v4.3.1
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftp
        port: 21
        local-dir: dist/
        server-dir: /public_html/
      continue-on-error: true

    - name: Final FTP Deploy (last try)
      if: failure()
      uses: SamKirkland/FTP-Deploy-Action@v4.3.1
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftp
        port: 21
        local-dir: dist/
        server-dir: /public_html/
